first
Bostanova/go-db-sql-final pull request #1
Opened 2024-06-28 21:25 UTC by Bostanova

2024-06-29 15:13 UTC, dirtymew requested changes
Привет Зухра

хорошая работа - но есть что поправить

см PR

2024-06-29 15:13 UTC, dirtymew commented on parcel.go
> +	//if err != nil {
тут нужно раскоментировать обработку ошибки

2024-06-29 15:13 UTC, dirtymew commented on parcel.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-06-29 15:13 UTC, dirtymew commented on parcel.go
> +	parcel, err := s.Get(number)
тут нужно сделать все одним запросом UPDATE

2024-06-29 15:13 UTC, dirtymew commented on parcel.go
> +	_, err = s.db.Exec("DELETE FROM parcel WHERE number = :number", sql.Named("number", number))
тоже самое - одним запросом без s.Get(number)

2024-06-29 15:13 UTC, dirtymew commented on parcel_test.go
> +	assert.Equal(t, stored.Client, parcel.Client)
проще структуры сравнить чем каждое поле

2024-06-29 15:13 UTC, dirtymew commented on parcel_test.go
> +	require.Equal(t, err, sql.ErrNoRows)
лучше так 
require.Error
assert.ErrorIs

2024-06-29 15:13 UTC, dirtymew commented on parcel_test.go
> +		assert.Equal(t, parcel.Client, p.Client)
тут тоже проще сравнить структуры 

или можно лучше в testify есть функции для работы с массивами - можно обойтись без цикла и мапы тут и все проверить одним assert-ом

2024-06-29 15:13 UTC, dirtymew commented on parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET status = :status", sql.Named("status", status))
тут неверно - нужно казать конкретную посылку которой нужно статус поменять

2024-06-29 15:13 UTC, dirtymew commented on parcel.go
> +	rows, err := s.db.Query("SELECT * FROM parcel WHERE client = :client", sql.Named("client", client))
лучше не использовать * а перечислить в нужном порядке нужные поля

2024-07-02 05:40 UTC, Bostanova commented on parcel_test.go
> +	assert.Equal(t, stored.Client, parcel.Client)
В структурах различается поле number, поскольку в тестовой структуре мы не заполняем его и он всегда равен 0.  Если сравнивать структуры, то они всегда не равны. Или я косячу при создании структур( Подскажешь что не так?

2024-07-02 08:07 UTC, dirtymew approved these changes
Зухра

задание выполнено - зачет

2024-07-02 08:07 UTC, dirtymew commented on parcel_test.go
> +	assert.Equal(t, stored.Client, parcel.Client)
@Bostanova по логике все ок - нужно просто обновить поле parcel.Number = id как ты и сделала

2024-11-07 20:18 UTC, merged